# Project: ’ª≤‚ ‘
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Stack.o main.o
LINKOBJ  = Stack.o main.o
LIBS     = -L"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/lib" -L"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/include" -I"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/include" -I"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/Program File/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = ’ª≤‚ ‘.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Stack.o: Stack.c
	$(CPP) -c Stack.c -o Stack.o $(CXXFLAGS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)
